### ISSUE TITLE
Multi Environment Craft Setup With Environment Variables

### ISSUE THREAD

**Issue by a-am** [deployingcraftcms/php-fpm#6]
With your setup using NGINX & PHP-FPM how would you allow environment variables to be used to setup the DB & General Configs?

**Comment by themccallister** [comment]
For local development, the best method is to include a `docker-compose.yml` file in that specific project. Such as `path/to/project/docker-compose.yml` which defines the ENV vars for container...

Here is an example, I do need to add an example to this repo as well. 

```yaml
version: '2'
services:

    nginx:
        image: nginx:latest
        // more config

    php-fpm:
        image: deployingcraftcms/php-fpm
        ports:
            - "9000:9000"
        // more config

    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - "./storage/database:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: SuperLongPassword!
            MYSQL_DATABASE: dev_projectname
            MYSQL_PASSWORD: Password1!
            MYSQL_USER: projectname
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
```

Does this make sense?

**Comment by a-am** [comment]
So if it is the CRAFTENV_ variables would this be set in nginx or php-fpm? 

```
nginx:
        image: nginx:latest
        environment:
                CRAFTENV_SITE_URL: stuff
                CRAFTENV_BASE_URL: stuff
```
